
-- return {
--   {
--     "hrsh7th/cmp-nvim-lsp",
--   },
--   {
--     "L3MON4D3/LuaSnip",
--     dependencies = {
--       "saadparwaiz1/cmp_luasnip",
--       "rafamadriz/friendly-snippets",
--     },
--   },
--   {
--     "hrsh7th/nvim-cmp",
--     config = function()
--       local cmp = require("cmp")
--       require("luasnip.loaders.from_vscode").lazy_load()
--
--       cmp.setup({
--         snippet = {
--           expand = function(args)
--             require("luasnip").lsp_expand(args.body)
--           end,
--         },
--         window = {
--           completion = cmp.config.window.bordered(),
--           documentation = cmp.config.window.bordered(),
--         },
--         mapping = cmp.mapping.preset.insert({
--           ["<C-d>"] = cmp.mapping.scroll_docs(-4),
--           ["<C-f>"] = cmp.mapping.scroll_docs(4),
--           ["<C-Space>"] = cmp.mapping.complete(),
--           ["<C-e>"] = cmp.mapping.abort(),
--           ["<CR>"] = cmp.mapping.confirm({ select = true }),
--         }),
--         sources = cmp.config.sources({
--           { name = "nvim_lsp" },
--           { name = "luasnip" }, -- For luasnip users.
--         }, {
--           { name = "buffer" },
--         }),
--       })
--     end,
--   },
-- }
-- local cmp = require("cmp")
--
-- -- Safe require for optional dependencies
-- local luasnip_ok, luasnip = pcall(require, "luasnip")
-- local lspkind_ok, lspkind = pcall(require, "lspkind")
--
-- -- Initialize snippets if available
-- if luasnip_ok then
--   require("luasnip.loaders.from_vscode").lazy_load()
-- end
--
-- cmp.setup({
--   snippet = {
--     expand = function(args)
--       if luasnip_ok then
--         luasnip.lsp_expand(args.body)
--       end
--     end,
--   },
--   window = {
--     completion = cmp.config.window.bordered(),
--     documentation = cmp.config.window.bordered(),
--   },
--   mapping = cmp.mapping.preset.insert({
--     ["<C-d>"] = cmp.mapping.scroll_docs(-4),
--     ["<C-f>"] = cmp.mapping.scroll_docs(4),
--     ["<C-Space>"] = cmp.mapping.complete(),
--     ["<C-e>"] = cmp.mapping.abort(),
--     ["<CR>"] = cmp.mapping.confirm({ select = true }),
--     ["<Tab>"] = cmp.mapping(function(fallback)
--       if cmp.visible() then
--         cmp.select_next_item()
--       elseif luasnip_ok and luasnip.expand_or_jumpable() then
--         luasnip.expand_or_jump()
--       else
--         fallback()
--       end
--     end, { "i", "s" }),
--     ["<S-Tab>"] = cmp.mapping(function(fallback)
--       if cmp.visible() then
--         cmp.select_prev_item()
--       elseif luasnip_ok and luasnip.jumpable(-1) then
--         luasnip.jump(-1)
--       else
--         fallback()
--       end
--     end, { "i", "s" }),
--   }),
--   sources = cmp.config.sources({
--     { name = "nvim_lsp" },
--     { name = "luasnip", keyword_length = 2 },
--     { name = "buffer", keyword_length = 3 },
--     { name = "path" },
--   }),
--   formatting = lspkind_ok and {
--     format = lspkind.cmp_format({
--       mode = "symbol_text",
--       maxwidth = 50,
--       ellipsis_char = "...",
--       before = function(entry, vim_item)
--         vim_item.menu = ({
--           nvim_lsp = "[LSP]",
--           luasnip = "[Snip]",
--           buffer = "[Buf]",
--           path = "[Path]",
--         })[entry.source.name]
--         return vim_item
--       end,
--     }),
--   } or nil,
--   sorting = {
--     comparators = {
--       cmp.config.compare.offset,
--       cmp.config.compare.exact,
--       cmp.config.compare.score,
--       cmp.config.compare.recently_used,
--       cmp.config.compare.locality,
--       cmp.config.compare.kind,
--       cmp.config.compare.sort_text,
--       cmp.config.compare.length,
--       cmp.config.compare.order,
--     },
--   },
-- })
-- local cmp = require("cmp")
-- local luasnip = require("luasnip")
-- local lspkind = require("lspkind")
--
-- cmp.setup({
--   snippet = {
--     expand = function(args)
--       luasnip.lsp_expand(args.body)
--     end,
--   },
--   mapping = cmp.mapping.preset.insert({
--     ["<C-d>"] = cmp.mapping.scroll_docs(-4),
--     ["<C-f>"] = cmp.mapping.scroll_docs(4),
--     ["<C-Space>"] = cmp.mapping.complete(),
--     ["<C-e>"] = cmp.mapping.abort(),
--     ["<CR>"] = cmp.mapping.confirm({ select = true }),
--   }),
--   sources = cmp.config.sources({
--     { name = "nvim_lsp" }, -- LSP completions
--     { name = "luasnip" }, -- Snippets
--     { name = "buffer" }, -- Current buffer words
--     { name = "path" }, -- Filesystem paths
--   }),
--   formatting = {
--     format = lspkind.cmp_format({
--       mode = "symbol_text",
--       maxwidth = 50,
--       ellipsis_char = "...",
--       before = function(entry, vim_item)
--         -- Add source icons
--         vim_item.menu = ({
--           nvim_lsp = "[LSP]",
--           luasnip = "[Snip]",
--           buffer = "[Buf]",
--           path = "[Path]",
--         })[entry.source.name]
--         return vim_item
--       end,
--     }),
--   },
--   -- Enable better sorting
--   sorting = {
--     comparators = {
--       cmp.config.compare.offset,
--       cmp.config.compare.exact,
--       cmp.config.compare.score,
--       cmp.config.compare.recently_used,
--       cmp.config.compare.locality,
--       cmp.config.compare.kind,
--       cmp.config.compare.sort_text,
--       cmp.config.compare.length,
--       cmp.config.compare.order,
--     },
--   },
-- })
